name: RiceBarMac
options:
    minimumXcodeGenVersion: 2.37.0
    bundleIdPrefix: com.ricebar
    developmentLanguage: en
    deploymentTarget:
        macOS: '14.0'
packages:
    HotKey:
        url: https://github.com/soffes/HotKey
        from: 0.1.3
    Yams:
        url: https://github.com/jpsim/Yams
        from: 5.0.6
settings:
    base:
        DEVELOPMENT_TEAM: ''
targets:
    RiceBarMac:
        type: application
        platform: macOS
        deploymentTarget: '14.0'
        sources:
            - path: App
        settings:
            base:
                PRODUCT_NAME: RiceBarMac
                PRODUCT_BUNDLE_IDENTIFIER: com.ricebar.RiceBarMac
                CODE_SIGN_STYLE: Automatic
                SWIFT_VERSION: 5.9
                INFOPLIST_FILE: App/Info.plist
                ENABLE_HARDENED_RUNTIME: YES
                ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
            configs:
                Debug:
                    CODE_SIGN_ENTITLEMENTS: App/Entitlements/RiceBarMac_Debug.entitlements
                    ENABLE_HARDENED_RUNTIME: NO
                    CODE_SIGNING_ALLOWED: NO
                Release:
                    CODE_SIGN_ENTITLEMENTS: App/Entitlements/RiceBarMac_Release.entitlements
                    ENABLE_HARDENED_RUNTIME: YES
        info:
            path: App/Info.plist
            properties:
                CFBundleName: RiceBarMac
                CFBundleDisplayName: RiceBarMac
                CFBundleIdentifier: com.ricebar.RiceBarMac
                CFBundleVersion: '1'
                CFBundleShortVersionString: '0.1.0'
                LSMinimumSystemVersion: '14.0'
                LSUIElement: true
                NSAppleEventsUsageDescription: RiceBarMac uses Apple Events to control Terminal/Alacritty and apply themes.
                NSDesktopFolderUsageDescription: RiceBarMac needs access to change your desktop wallpaper.
        dependencies:
            - package: HotKey
            - package: Yams
    RiceBarMacTests:
        type: bundle.unit-test
        platform: macOS
        sources:
            - path: Tests
        settings:
            base:
                GENERATE_INFOPLIST_FILE: YES
                PRODUCT_BUNDLE_IDENTIFIER: com.ricebar.RiceBarMacTests
        dependencies:
            - target: RiceBarMac
schemes:
    RiceBarMac:
        build:
            targets:
                RiceBarMac: all
        run:
            config: Debug
        archive:
            config: Release
        test:
            targets:
                - RiceBarMacTests
            config: Debug
